# personal aliases
# alias vim='nvim'

# git related aliases
alias gls='git ls-files'
alias glog='git log --oneline'
alias gs='git status'
alias gb='git branch -a'
alias ga='git add *'

# colorful 'ls' command
export TERM=xterm-color
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
export GREP_OPTIONS='--color=auto'
alias ls='ls -GFh'

# color of the terminal itself
export TERM="xterm-color" 
export PS1='\[\e[0;33m\]\u\[\e[0m\]@\[\e[0;32m\]\h\[\e[0m\]:\[\e[0;34m\]\w\[\e[0m\]\$ '

# TMUX error fix
# [warn]: kq_init: detected broken kqueue; not using.: File exists
export EVENT_NOKQUEUE=1

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.bash_aliases_s ]; then
    . ~/.bash_aliases_s
fi

