syntax enable
set background=dark
colorscheme Tomorrow-Night

set number
set tabstop=4
set langmenu=en_US
let $LANG = 'en_US'
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

set hlsearch
set colorcolumn=80

set shiftwidth=4
set softtabstop=0 expandtab
set tags=./tags,tags;$HOME

